### PR TITLE
url, staticfiles and template name provider

### PR DESCRIPTION
**Pull request by WellingtonNico**
hello! 
You have such an amazing extension, but there are some features that I consider are missing!
I'm a Django and VSCode lover and I'd like to share my functionalities with you:

* template names provider
* url names provider
* staticfiles provider
* url definition provider

I hope you like! I also put some gifs in the REDME.

### CODE REVIEW

**Comment by almahdi404** [comment]
Great job! That's a lot of features, and I really appreciate the effort you've put into this.

I'll definitely merge it after reviewing the code.

Just one small request, I noticed the gifs are a bit blurry, and I’m guessing you used ezgif.com to generate them. If possible, could you try using a different tool for sharper results?

Thanks again for your hard work!

**Comment by WellingtonNico** [comment]
Thank you for your answer!

Could you indicate a better tool to generate a gift? I'd like it to be a website..

**Comment by WellingtonNico** [comment]
Thank you for your answer!

Could you indicate a better tool to generate a gift? I'd like it to be a website..

**Comment by almahdi404** [comment]
I guess, i used https://cloudconvert.com

**Comment by WellingtonNico** [comment]
> I guess, i used https://cloudconvert.com

tell me about now, are the gifs good?

**Comment by almahdi404** [comment]
There are still boxes in gifs, which shouldn't be there. Did you use **cloudconvert**?

**Comment by WellingtonNico** [comment]
yes I used, and the video resolution is 1532 × 992, would you like me to send you the original videos so you can try?

**Comment by WellingtonNico** [comment]
wait a moment, are you sure you saw the updated version?
there are only two gifs and they are very good inside github.. 🤔🤔

https://github.com/WellingtonNico/code-django/tree/url-name-provider

**Comment by almahdi404** [comment]
How are you gonna send them?

**Comment by almahdi404** [comment]
> wait a moment, are you sure you saw the updated version? there are only two gifs and they are very good inside github.. 🤔🤔
> 
> https://github.com/WellingtonNico/code-django/tree/url-name-provider

You can see boxes in the gifs you added, which aren't there in the top gif which i added.

**Comment by WellingtonNico** [comment]
here the videos:
https://drive.google.com/drive/folders/199YtnLg9Qr4mHxZdbOjgLpwyzKTs9gG7?usp=sharing

**Comment by almahdi404** [comment]
Please remove the gifs from the images folder.

**Comment by WellingtonNico** [comment]
> Please remove the gifs from the images folder.

done

**Comment by almahdi404** [comment]
Thanks! I will merge it after a little review and then manage the rest.

**Comment by WellingtonNico** [comment]
> Thanks! I will merge it after a little review and then manage the rest.

Great! I'm looking forward for this update, I use it every day on my own extension, but it's not in the store to download, so I thought it would be better to join my code into yours!

**Comment by WellingtonNico** [comment]
hello, can you tell me how much time it takes for the update to be available in vscode?

**Comment by almahdi404** [comment]
It takes approx 5 minutes to be available for download after publishing. I will try to publish it within an hour.

**Pull request merged**
